cache: 
  directories: 
    - "$HOME/.m2"

language: java
jdk:
  - openjdk8

install: true

script:
  - echo "git clone and build Leaf project..."
  - git clone https://github.com/Meituan-Dianping/Leaf
  - cd Leaf
  - mvn clean package install -Dmaven.test.skip=true -pl leaf-core
  - cd ..
  - echo "build sharding-keygen-leaf project..."
  - mvn clean package install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
  - echo "Build successfully."
